name: Trigger Phab Review Events

on:
  push:
    branches:
    - 'phab-diff-*'

jobs:
  trigger-libcxx-builders:
  runs-on: [ubuntu-latest]
  steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Trigger Event
      run: |
        curl -X POST \
        https://api.github.com/repos/efcs/libcxx-builders/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u ${{ secrets.efcs_libcxx_builder_token }} \
        --data '{ \
          "event_type": "precommit_test_request", \
          "client_payload": { \
            "repository": "'"$GITHUB_REPOSITORY"'", \
            "ref": "'"$GITHUB_REF"'", \
            "head_ref": "'"$GITHUB_HEAD_REF"'", \
            "base_ref": "'"$GITHUB_BASE_REF"'" \
          }}'


